In [4]:
import pandas as pd
import numpy as np
# create sample datasets
data={
    "Name":["Naveen","Akash","Devika","Shreya","Nithin","Komal","Bhuvan","Kaveri","Vasthsal","Disha"],
    "City":["Bengaluru","Mysuru","Bengaluru","Hubli","Bengaluru","Mysuru","Hubli","Bengaluru","Mysuru","Bengaluru"],
    "Marks":[85,72,91,55,78,65,48,88,70,92],
    "Age":[20,21,19,22,20,21,20,19,21,20]
    
}

df=pd.DataFrame(data)
df

       Name       City  Marks  Age
0    Naveen  Bengaluru     85   20
1     Akash     Mysuru     72   21
2    Devika  Bengaluru     91   19
3    Shreya      Hubli     55   22
4    Nithin  Bengaluru     78   20
5     Komal     Mysuru     65   21
6    Bhuvan      Hubli     48   20
7    Kaveri  Bengaluru     88   19
8  Vasthsal     Mysuru     70   21
9     Disha  Bengaluru     92   20

In [5]:
#groupBy city-average marks per city
city_avg=df.groupby("City")["Marks"].mean()
print("Average Marks per city:")
print(city_avg)

Average Marks per city:
City
Bengaluru    86.8
Hubli        51.5
Mysuru       69.0
Name: Marks, dtype: float64

In [6]:
#Multiple groupby operations
print("Sum of marks per city:")
print(df.groupby("City")["Marks"].sum())

print("\nCount of students per city:")
print(df.groupby("City")["Marks"].count())

print("\nMaximum marks per city:")
print(df.groupby("City")["Marks"].max())


print("\nMinimum marks per city:")
print(df.groupby("City")["Marks"].min())

Sum of marks per city:
City
Bengaluru    434
Hubli        103
Mysuru       207
Name: Marks, dtype: int64

Count of students per city:
City
Bengaluru    5
Hubli        2
Mysuru       3
Name: Marks, dtype: int64

Maximum marks per city:
City
Bengaluru    92
Hubli        55
Mysuru       72
Name: Marks, dtype: int64

Minimum marks per city:
City
Bengaluru    78
Hubli        48
Mysuru       65
Name: Marks, dtype: int64

In [7]:
#Multiple Aggregations at once using agg()
city_summary=df.groupby("City")["Marks"].agg(["mean","max","min","count"])
city_summary.columns=["Average","Highest","Lowest","Studentcount"]
print("city wise summary:")
print(city_summary)

city wise summary:
           Average  Highest  Lowest  Studentcount
City
Bengaluru     86.8       92      78             5
Hubli         51.5       55      48             2
Mysuru        69.0       72      65             3

In [16]:
city_average_age=df.groupby("City")["Age"].mean()
print(city_average_age)

City
Bengaluru    19.6
Hubli        21.0
Mysuru       21.0
Name: Age, dtype: float64

In [15]:
city_average=df.groupby("City")["Age"].agg(["mean","max","min"])
city_average.columns=["Average_age","Highest_age","Lowest_age"]
print("city average age summary:")
print(city_average)

city average age summary:
           Average_age  Highest_age  Lowest_age
City
Bengaluru         19.6           20          19
Hubli             21.0           22          20
Mysuru            21.0           21          21

In [17]:
#describe()-full explanation
print("Full describe():")
print(df.describe())

Full describe():
           Marks        Age
count  10.000000  10.000000
mean   74.400000  20.300000
std    15.211107   0.948683
min    48.000000  19.000000
25%    66.250000  20.000000
50%    75.000000  20.000000
75%    87.250000  21.000000
max    92.000000  22.000000

In [19]:
#Individual statistics
print("Mean marks:",df["Marks"].mean())
print("Median marks:",df["Marks"].median())
print("Std Deviations:",df["Marks"].std())
print("variance:",df["Marks"].var())
print("25th percentile:",df["Marks"].quantile(0.25))
print("75th percentile:",df["Marks"].quantile(0.75))
print("correlation between age and marks:")
print(df[["Age","Marks"]].corr())

Mean marks: 74.4
Median marks: 75.0
Std Deviations: 15.211107052998404
variance: 231.3777777777778
25th percentile: 66.25
75th percentile: 87.25
correlation between age and marks:
            Age     Marks
Age    1.000000 -0.656017
Marks -0.656017  1.000000

In [20]:
#value Counts
print("Student per City:")
print(df["City"].value_counts())

print("\nPercentage per city:")
print(df["City"].value_counts(normalize=True)*100)

Student per City:
City
Bengaluru    5
Mysuru       3
Hubli        2
Name: count, dtype: int64

Percentage per city:
City
Bengaluru    50.0
Mysuru       30.0
Hubli        20.0
Name: proportion, dtype: float64

In [25]:
print("Full describe():")
print(df["Marks"].describe())

Full describe():
count    10.000000
mean     74.400000
std      15.211107
min      48.000000
25%      66.250000
50%      75.000000
75%      87.250000
max      92.000000
Name: Marks, dtype: float64

In [26]:
print("Median marks:",df["Marks"].median())
print("Student per City:")
vrv=df["City"].value_counts()
print(vrv)
print(vrv.head(1))

Median marks: 75.0
Student per City:
City
Bengaluru    5
Mysuru       3
Hubli        2
Name: count, dtype: int64
City
Bengaluru    5
Name: count, dtype: int64

In [29]:
#data explration
#Top 3 Students by Marks
top3=df.nlargest(3,"Marks")
print("top 3 students:")
print(top3[["Name","Marks","City"]])

#Botttom 3 students by Marks
bottom3=df.nsmallest(3,"Marks")
print("Bottom 3 students:")
print(bottom3[["Name","Marks","City"]])

top 3 students:
     Name  Marks       City
9   Disha     92  Bengaluru
2  Devika     91  Bengaluru
7  Kaveri     88  Bengaluru
Bottom 3 students:
     Name  Marks    City
6  Bhuvan     48   Hubli
3  Shreya     55   Hubli
5   Komal     65  Mysuru

In [30]:
#conditional analysis
#above average students
avg_marks=df["Marks"].mean()
above_avg=df[df["Marks"]>avg_marks]
below_avg=df[df["Marks"]<avg_marks]

print(f"Class average:{avg_marks:.2f}")
print(f"\nStudents above average({len(above_avg)}):")
print(above_avg[["Name","Marks"]])

print(f"\nStudents below average({len(below_avg)}):")
print(below_avg[["Name","Marks"]])

Class average:74.40

Students above average(5):
     Name  Marks
0  Naveen     85
2  Devika     91
4  Nithin     78
7  Kaveri     88
9   Disha     92

Students below average(5):
       Name  Marks
1     Akash     72
3    Shreya     55
5     Komal     65
6    Bhuvan     48
8  Vasthsal     70

In [34]:
#Trend:city-wise performance
city_performance=df.groupby("City")["Marks"].mean().sort_values(ascending=False)
print("City Performance ranking (Average marks):")
print(city_performance)

#Trend:Pass rate per city
df["Result"]=df["Marks"].apply(lambda x:"Pass" if x>=60 else "Fail")
pass_rate=df.groupby("City")["Result"].apply(lambda x:(x=="Pass").sum()/len(x)*100)
print("\nPass Rate Per City(%)")
print(pass_rate.round(2))

City Performance ranking (Average marks):
City
Bengaluru    86.8
Mysuru       69.0
Hubli        51.5
Name: Marks, dtype: float64

Pass Rate Per City(%)
City
Bengaluru    100.0
Hubli          0.0
Mysuru       100.0
Name: Result, dtype: float64

In [38]:
top3=df.nlargest(2,"Marks")
print("top 3 students:")
print(top3[["Name","Marks","City"]])
bottom3=df.nsmallest(2,"Marks")
print("Bottom 3 students:")
print(bottom3[["Name","Marks","City"]])

top 3 students:
     Name  Marks       City
9   Disha     92  Bengaluru
2  Devika     91  Bengaluru
Bottom 3 students:
     Name  Marks   City
6  Bhuvan     48  Hubli
3  Shreya     55  Hubli

In [41]:
avg_marks=df["Marks"].mean()
above_avg=df[df["Marks"]>avg_marks]
below_avg=df[df["Marks"]<avg_marks]
print(f"average marks:",avg_marks)
print(f"Students above average({len(above_avg)})")
print(f"\nStudents below average({len(below_avg)})")

average marks: 74.4
Students above average(5)

Students below average(5)

In [50]:
print("="*50)
print("     Student Summary Report")
print("="*50)

print(f"\nTotal Students: {len(df)}")
print(f"Average Marks: {df["Marks"].mean():.2f}")
print(f"Highest Marks: {df['Marks'].max()}")
print(f"Lowest Marks: {df['Marks'].min()}")
print(f"Median Marks: {df['Marks'].median()}")

print("\n--- Pass/Fail Summary ---")
result_counts = df["Result"].value_counts()
for result, count in result_counts.items():
    print(f"{result}: {count} students")

print("\n--- Grade Summary ---")
df["Grade"] = df["Marks"].apply(lambda x: "A" if x >= 80 else "B" if x >= 60 else "C")
grade_counts = df["Grade"].value_counts().sort_index()
for grade, count in grade_counts.items():
    print(f"Grade {grade}: {count} students")

print("\n--- City-wise Average Marks ---")
city_avg = df.groupby("City")["Marks"].mean().sort_values(ascending=False)
for city, avg in city_avg.items():
    print(f"{city}: {avg:.2f}")

print("\n--- Top 3 Students ---")
top3 = df.nlargest(3, "Marks")
for i, row in top3.iterrows():
    print(f"{row['Name']} - {row['Marks']} marks ({row['City']})")

print("\n--- Students Needing Attention (Marks < 60) ---")
weak = df[df["Marks"] < 60]
if len(weak) == 0:
    print("All Students Passed.")
else:
    for i, row in weak.iterrows():
        print(f"{row['Name']} - {row['Marks']} marks")

print("="*50)
print("   END OF REPORT")
print("="*50)

SyntaxError: f-string: unmatched '[' (1585557041.py, line 6)

In [46]:
#Save summary to csv
summary_data={
    "Metric":[
        "Total Students",
        "Average Marks",
        "Highest Marks",
        "Lowest Marks",
        "Median Marks",
        "Pass Count",
        "Fail Count"
    ],
    "Value":[
        len(df),
        round(df["Marks"].mean(),2),
        df["Marks"].max(),
        df["Marks"].min(),
        df["Marks"].median(),
        len(df[df["Result"]=="pass"]),
        len(df[df["Result"]=="Fail"])
    ]
}

summary_df=pd.DataFrame(summary_data)
summary_df.to_csv("students_summary_report.csv",index=False)
print("Sumarry report saved to student_summary_report.csv ")
summary_df

Sumarry report saved to student_summary_report.csv

           Metric  Value
0  Total Students   10.0
1   Average Marks   74.4
2   Highest Marks   92.0
3    Lowest Marks   48.0
4    Median Marks   75.0
5      Pass Count    0.0
6      Fail Count    2.0

In [64]:
sales_data = {

    "Product": ["Pen","Notebook","Pen","Pencil","Notebook",

                "Pen","Pencil","Notebook","Pen","Pencil"],

    "City": ["Bengaluru","Mysuru","Hubli","Bengaluru","Bengaluru",

             "Mysuru","Hubli","Bengaluru","Hubli","Mysuru"],

    "Quantity": [10, 3, 7, 15, 5, 8, 12, 4, 6, 9],

    "Price": [20, 50, 20, 5, 50, 20, 5, 50, 20, 5]

}
df=pd.DataFrame(sales_data)
df["TotalAmount"]=df["Quantity"]*df["Price"]
print(df["TotalAmount"])


print("total  amount:")
print(df.groupby("Product")["Price"].sum())

print("\ntotal Quantity:")
print(df.groupby("Product")["Price"].count())

print("\naverage price")
print(df.groupby("Product")["Price"].mean())

print("\n using agg()")
vrv=df.groupby("Product")["Price"].agg(["mean","max","min","count"])
vrv.columns=["mean","Highest price","Lowest price","total products"]
print(vrv)
print("total  amount by city :")
print(df.groupby("City")["Price"].sum())

print("\ntotal transactions:")
print(df.groupby("City")["Price"].count())

print("\n using agg()")
vrv1=df.groupby("City")["Price"].agg(["mean","max","min","count"])
vrv1.columns=["mean","Highest price","Lowest price","total transactions"]
print(vrv1)

0    200
1    150
2    140
3     75
4    250
5    160
6     60
7    200
8    120
9     45
Name: TotalAmount, dtype: int64
total  amount:
Product
Notebook    150
Pen          80
Pencil       15
Name: Price, dtype: int64

total Quantity:
Product
Notebook    3
Pen         4
Pencil      3
Name: Price, dtype: int64

average price
Product
Notebook    50.0
Pen         20.0
Pencil       5.0
Name: Price, dtype: float64

 using agg()
          mean  Highest price  Lowest price  total products
Product
Notebook  50.0             50            50               3
Pen       20.0             20            20               4
Pencil     5.0              5             5               3

In [71]:
print(df["TotalAmount"].describe())
print("Mean:", df["TotalAmount"].mean())
print("Median:", df["TotalAmount"].median())
print("Std Dev:", df["TotalAmount"].std())
print(df.nlargest(3, "TotalAmount"))
print(df.nsmallest(3, "TotalAmount"))
print("Highest sales product:",df.groupby("Product")["TotalAmount"].sum().idxmax())
print("Highest sales city:",df.groupby("City")["TotalAmount"].sum().idxmax())

count     10.000000
mean     140.000000
std       66.541549
min       45.000000
25%       86.250000
50%      145.000000
75%      190.000000
max      250.000000
Name: TotalAmount, dtype: float64
Mean: 140.0
Median: 145.0
Std Dev: 66.54154925892377
    Product       City  Quantity  Price  TotalAmount
4  Notebook  Bengaluru         5     50          250
0       Pen  Bengaluru        10     20          200
7  Notebook  Bengaluru         4     50          200
  Product       City  Quantity  Price  TotalAmount
9  Pencil     Mysuru         9      5           45
6  Pencil      Hubli        12      5           60
3  Pencil  Bengaluru        15      5           75
Highest sales product: Pen
Highest sales city: Bengaluru

In [73]:
revenue_product = df.groupby("Product")["TotalAmount"].sum()
revenue_city = df.groupby("City")["TotalAmount"].sum()

summary_data = {
    "Metric": [
        "Total Transactions",
        "Total Revenue",
        "Average Transaction Amount",
        "Best Selling Product",
        "Best Performing City"
    ],
    "Value": [
        len(df),
        df["TotalAmount"].sum(),
        round(df["TotalAmount"].mean(), 2),
        revenue_product.idxmax(),
        revenue_city.idxmax()
    ]
}

summary_df = pd.DataFrame(summary_data)

summary_df.to_csv("sales_summary_report.csv", index=False)

print("Summary report saved to sales_summary_report.csv")
summary_df

Summary report saved to sales_summary_report.csv

                       Metric      Value
0          Total Transactions         10
1               Total Revenue       1400
2  Average Transaction Amount      140.0
3        Best Selling Product        Pen
4        Best Performing City  Bengaluru